<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Adapters\Infrastructure.Data.Adapters.InMemory\Infrastructure.Data.Adapters.InMemory.csproj" />
  </ItemGroup>

</Project>
